export const REGISTER_REQUESTED = 'AUTH/REGISTER_REQUESTED';
export const REGISTER_SUCCESS = 'AUTH/REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH/REGISTER_FAIL';
export const LOGIN_FAIL = 'AUTH/LOGIN_FAIL';
export const LOGIN_SUCCESS = 'AUTH/LOGIN_SUCCESS';
export const LOGIN_REQUESTED = 'AUTH/LOGIN_REQUESTED';